Feature/live chat getter
VictoriaLabs/bot-kick pull request #2
Opened 2023-12-20 11:45 UTC by KAymeric

2023-12-20 17:04 UTC, LoanF requested changes

2023-12-20 17:04 UTC, LoanF commented on src/package-lock.json
> +        "ws": "^8.12.1"
Utiliser seulement socket.io

2024-01-14 13:46 UTC, MazBazDev approved these changes

2024-01-14 17:57 UTC, LoanF approved these changes

2024-01-14 17:58 UTC, LoanF commented
feat : live chat getter

2024-01-14 17:58 UTC, merged